### ISSUE TITLE
启动报错无法正常打开使用

### ISSUE THREAD

**Issue by coffeehb** [SafeGroceryStore/MDUT#10]
## 环境
win10 x64，JDK9.0.4 和 JDK1.8

### JDK9.0.4 启动成功，添加mysql报错截图

![image](https://user-images.githubusercontent.com/5829776/118012666-e3de0c80-b383-11eb-9faf-a5407a05490f.png)

### JDK8 启动时报错

 ![image](https://user-images.githubusercontent.com/5829776/118013030-4505e000-b384-11eb-8686-a1257c34b9aa.png)

**Comment by Ch1ngg** [comment]
### #1 
JDK 8 以上无法正常运行。

### #2 
这边测试好几个 JDK 环境都可以正常打开。

Mac 本机环境 java
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

Win 7 测试环境 java
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
请换个版本试试

**Comment by Ch1ngg** [comment]
集成 JAVA 环境的软件包已更新。[点击下载](https://github.com/SafeGroceryStore/MDUT/releases/tag/v2.0)
