### ISSUE TITLE
redis利用时报错：无写入权限。

### ISSUE THREAD

**Issue by xslzlccc** [SafeGroceryStore/MDUT#26]
（此问题在攻防比赛利用时发现）
部分redis数据库没有打开写入权限，在写入计划任务或公钥时会报错：
(error) READONLY You can't write against a read only replica
[图片]
只需要使用config set slave-read-only no命令开启写入权限即可，希望不要因为这个问题漏掉shell呀

**Comment by Ch1ngg** [comment]
这边抽时间复测一下，但是图片是啥能补全吗

**Comment by j1anFen** [comment]
已增加该语句和清理时恢复该语句功能。
