### ISSUE TITLE
远程执行马子，超时连接，软件需要重新进入后连接

### ISSUE THREAD

**Issue by SnowMeteors** [SafeGroceryStore/MDUT#27]
## 系统环境
 - OS: Win 10 x64

## Bug 详细描述
![image](https://user-images.githubusercontent.com/47601098/137860459-b816a13f-62f7-48b6-91a6-dab177eaa071.png)
如上图，我远程执行马子，msf能正常上线
![image](https://user-images.githubusercontent.com/47601098/137860498-a54af9b2-2533-42ad-a446-6e0cd7e7708c.png)
但此软件出现连接超时警告
我需要重新打开一个连接才能正常使用
![image](https://user-images.githubusercontent.com/47601098/137860625-e5ce22b9-f589-45c8-89b2-25940c11f28a.png)
![image](https://user-images.githubusercontent.com/47601098/137860657-b5066b9e-b432-46ac-ac9b-2f16da13bec8.png)
如果我频繁远程执行exe文件，每次都要重新打开去连接，希望改进一下

**Comment by Ch1ngg** [comment]
试试用 start 命令看看
