### ISSUE TITLE
建议设置一个默认编码

### ISSUE THREAD

**Issue by shadow1ng** [SafeGroceryStore/MDUT#28]
建议设置一个默认编码，这样命令执行时，不会直接弹窗、执行失败

**Comment by shadow1ng** [comment]
然后能否做一个断线重连功能？
经常几秒钟没操作，就断开了，然后提示java.sql.SQLException: Invalid state, the Connection object is closed.

**Comment by Ch1ngg** [comment]
默认编码已设置。另一个bug正在尝试解决
