### ISSUE TITLE
windows的redis主从复制

### ISSUE THREAD

**Issue by learner-ing** [SafeGroceryStore/MDUT#32]
希望将windows的redis主从复制添加到项目中。

**Comment by Ch1ngg** [comment]
刚看到你的项目，我觉得我们可以交流一下 Redis 该如何增强

**Comment by learner-ing** [comment]
> 刚看到你的项目，我觉得我们可以交流一下 Redis 想要增长

只需要将exp.so替换为exp.dll就行了，但似乎在windows server中无法使用。目前还不知道原因。

**Comment by Ch1ngg** [comment]
> > 刚看到你的项目，我觉得我们可以交流一下 Redis 想要增长
> 
> 只需要将exp.so替换为exp.dll就行了，但似乎在windows server中无法使用。目前还不知道原因。

那我搭建环境测试一下看看，Redis Windows 功能这块主要问题是兼容性太差，我们当时考虑就不想添加了。

**Comment by Ch1ngg** [comment]
经测试翻车率有点高，考虑到实战环境的问题，暂时不添加了，谢谢师傅的 Issue
