### ISSUE TITLE
师傅您好，按您所说的编译方式遇见如下报错

### ISSUE THREAD

**Issue by 98Kstar** [SafeGroceryStore/MDUT#39]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/41816999/162552093-6d6f2f80-a0f1-4f12-88b5-d2ad14150926.png">

我使用的是mac系统，编译jdk版本是java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
希望师傅不吝赐教

**Comment by 98Kstar** [comment]
编译方法是您发的yuque上的方式。

**Comment by ttsite** [comment]
> 编译方法是你发的yuque上的方式。

编译方式在哪里发个地址看看

**Comment by 98Kstar** [comment]
报错以下：
程序包javafx.application不存在
程序包javafx.beans.value不存在
程序包javafx.beans.value不存在
程序包javafx.event不存在
程序包javafx.fxml不存在
程序包javafx.fxml不存在
程序包javafx.scene.image不存在
程序包javafx.scene.image不存在
程序包javafx.stage不存在
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
找不到符号
程序包javafx.scene.control不存在
是我缺包的问题吗

**Comment by 98Kstar** [comment]
> > 编译方法是你发的yuque上的方式。
> 
> 编译方式在哪里发个地址看看

https://www.yuque.com/u21224612/nezuig/ays2ai

**Comment by ttsite** [comment]
没有target

**Comment by Ch1ngg** [comment]
只支持JDK8

**Comment by Ch1ngg** [comment]
> 没有target

target 目录是你自己编译后自动生成的
