### ISSUE TITLE
UDF提权的bug

### ISSUE THREAD

**Issue by Redem6ti0n** [SafeGroceryStore/MDUT#4]
UDF提权，清楚痕迹之后可能temp文件没删除，再次提权可能会失败
![a](https://user-images.githubusercontent.com/59553855/117384374-60509580-af15-11eb-972b-00ef8b17a7ac.png)

UDF提权后 执行exe的cs马，由于没有返回结果会卡死

**Comment by Ch1ngg** [comment]
这个不应该啊，因为每次都会随机一个temp值进行重新提权的，按道理来说应该只会 function 存在。

2021年5月7日 上午9:22，ゴジラ ***@***.******@***.***>> 写道：



UDF提权，清楚痕迹之后可能temp文件没删除，再次提权可能会失败
[a]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59553855%2F117384374-60509580-af15-11eb-972b-00ef8b17a7ac.png&data=04%7C01%7C%7C4aa869927e564b29b85408d910f68694%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637559473267282064%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jXaot%2BNkwPJn18FnFVkKxl7GX1fcTT8lqjNGV5%2F1VPo%3D&reserved=0>

UDF提权后 执行exe的cs马，由于没有返回结果会卡死

**Comment by Ch1ngg** [comment]
已修复，下个版本发布
