### ISSUE TITLE
M1 连接报错

### ISSUE THREAD

**Issue by 188150486** [SafeGroceryStore/MDUT#61]
## 系统
 - OS: MacOs
 - JavaVersion  jdk8

## 软件版本
 - Version 2.1.1

## Bug 详细描述

<img width="444" alt="image" src="https://user-images.githubusercontent.com/32973396/222080551-6456dead-4f1a-4a53-a733-6966e6b6d6b5.png">

**Comment by Ch1ngg** [comment]
排查电脑网络问题
