### ISSUE TITLE
添加完成MSSQL后出现错误提示

### ISSUE THREAD

**Issue by ttsite** [SafeGroceryStore/MDUT#7]
添加完成MSSQL后出现错误提示

![d](https://user-images.githubusercontent.com/43260559/117753791-aa09ea80-b24b-11eb-9a0b-9d66cac8cc63.png)

**Comment by Ch1ngg** [comment]
版本已发布，请测试是否还存在，后续 issue 希望按照要求填写，谢谢！:)

**Comment by ttsite** [comment]
![cc](https://user-images.githubusercontent.com/43260559/117759324-2d303e00-b256-11eb-8616-f17b5fdebdd7.png)
了解下次发的时侯一点注意要求,谢谢你的回复。还是这样的情况

**Comment by Ch1ngg** [comment]
能否贴上 java 版本，这边 mac 和 windows 7 测试是没有问题

**Comment by ttsite** [comment]
2.0版本以前的我机器可以正常打开
![11](https://user-images.githubusercontent.com/43260559/117760973-23f4a080-b259-11eb-85fd-005bc40dabfb.png)

**Comment by Ch1ngg** [comment]
使用 jdk8。8以上无法运行。
