### ISSUE TITLE
连接MySQL报错，用Navicat那些连是可以的

### ISSUE THREAD

**Issue by klmyssn** [SafeGroceryStore/MDUT#8]
## 系统环境
 - OS: Win 10 x64
 - java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

## 软件版本
 - Version MDUT-v2.0.1

## Bug 详细描述

用Navicat连正常的 
![RQ H9YX~W DFZX@9QZ003QN](https://user-images.githubusercontent.com/37890522/117786528-2d413580-b278-11eb-9ee8-fa47c41c3195.png)
用软件配置好地址链接报错：
![39M2MBI{83~CAUM6J9SRY 9](https://user-images.githubusercontent.com/37890522/117786569-3a5e2480-b278-11eb-8890-ebcb331718de.png)
具体i报错信息：
java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at Dao.MysqlDao.<init>(MysqlDao.java:74)
	at Controller.MysqlController.lambda$initialize$2(MysqlController.java:93)
	at java.lang.Thread.run(Unknown Source)

![V579HSYZ897_QVCT1X1@{@L](https://user-images.githubusercontent.com/37890522/117786625-4a760400-b278-11eb-89ef-054d02744f61.png)
辛苦师傅了！！！

**Comment by Ch1ngg** [comment]
已知悉，Bug 是中文问题导致 config.yaml 内容编码不一致，读取时候乱码了。
